format = """
[░▒▓](#d65d03)\
[ 󰍲 ](bg:#d79921 fg:#fbf1c7)\
[](bg:#d5c4a1 fg:#d79921)\
$directory\
[](fg:#d5c4a1 bg:#8ec07c)\
$git_branch\
$git_status\
[](fg:#8ec07c bg:#3c3836)\
$nodejs\
$cmd_duration\
[](fg:#3c3836 bg:#282828)\
$python\
[ ](fg:#282828)\
"""
# $character"""
#\n$character"""

command_timeout=3000

[directory]
style = "fg:#3c3836 bg:#d5c4a1"
format = "[ $path ]($style)"
#truncation_length = 3
#truncation_symbol = "…/"

[directory.substitutions]
"~/Documents" = "󰈙" # "Documents" = "..." , then you should remove the "~"="..."
"~/Downloads" = " "
"~/Music" = " "
"~/Pictures" = " "
"~/.config" = ""
"~/Git" = "󰊢"
"~" = ""

[git_branch]
symbol = ""
style = "bg:#8ec07c"
format = '[[ $symbol $branch ](fg:#fbf1c7 bg:#8ec07c)]($style)'

[git_status]
style = "bg:#8ec07c"
format = '[[($all_status$ahead_behind )](fg:#fbf1c7 bg:#8ec07c)]($style)'

[nodejs]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d5c4a1 bg:#282828)]($style)'

[rust]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d5c4a1 bg:#282828)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d5c4a1 bg:#282828)]($style)'

[php]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d5c4a1 bg:#282828)]($style)'

[python]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d5c4a1 bg:#282828)]($style)'

[cmd_duration]
disabled = false
style = "bg:#1d2230"
format = '[[  $duration ](fg:#d5c4a1 bg:#282828)]($style)'
